name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: npm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/cache@v2
        with:
          path: "~/.npm-store"
          key: ${{ runner.os }}-node-${{ hashFiles('**/npm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install --frozen-lockfile
      - run: npm run ci
